package com.github.ptosda.projectvalidationmanager.database.repositories

import com.github.ptosda.projectvalidationmanager.database.entities.DependencyLicense
import com.github.ptosda.projectvalidationmanager.database.entities.DependencyLicensePk
import org.springframework.data.repository.PagingAndSortingRepository
import org.springframework.stereotype.Repository

@Repository
interface DependencyLicenseRepository : PagingAndSortingRepository<DependencyLicense, DependencyLicensePk>